apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logging-agent
  labels:
    app.kubernetes.io/name: logging-agent
    app.kubernetes.io/component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-agent
subjects:
  - kind: ServiceAccount
    name: logging-agent
    namespace: logging-system
