apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logging-agent.fullname" . }}-config
  namespace: {{ include "logging-agent.namespace" . }}
  labels:
    {{- include "logging-agent.labels" . | nindent 4 }}
data:
  configFile: |
    agent:
      logLevel: info

      outputPath: /var/log/agent.log

      # Will be taken from k8s env vars
      nodeName: ""
      podName: ""
      namespace: ""
    
      collection:
        interval: "1s"
        batchSize: 100
        maxLineLength: 16384
        logChanSize: 10000
        logPaths:
          - /var/log/containers/*.log
          - /var/log/pods/**/*.log

    loki:
      url: {{ .Values.loki.url | quote }}

    httpServer:
      address: {{ .Values.httpServer.address | quote }}
      readTimeout: 5s
      writeTimeout: 10s
      idleTimeout: 15s
