apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logging-agent.fullname" . }}
  namespace: {{ include "logging-agent.namespace" . }}
  labels:
    {{- include "logging-agent.labels" . | nindent 4 }}
