apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logging-agent
  labels:
    app.kubernetes.io/name: logging-agent
    app.kubernetes.io/component: monitoring
rules:
  # Read pods to get container metadata
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
  # Read pod logs
  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get
      - list
  # Read namespaces for filtering
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
