apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-agent-config
  namespace: logging-system
  labels:
    app.kubernetes.io/name: logging-agent
    app.kubernetes.io/component: monitoring
data:
  configFile: |
    agent:
      logLevel: info

      outputPath: /var/log/agent.log

      # Will be taken from k8s env vars
      nodeName: ""
      podName: ""
      namespace: ""
    
      collection:
        interval: "10s"
        batchSize: 100
        maxLineLength: 16384
        logChanSize: 10000
        logPaths:
          - /var/log/containers/*.log
          - /var/log/pods/**/*.log

    httpServer:
      address: ":8080"
      readTimeout: 5s
      writeTimeout: 10s
      idleTimeout: 15s
